### PR TITLE
CI: switch from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by ctrueden**
After merging this, you will still need to add the organization secrets to kapoorlab. If you add me to the organization as an owner temporarily, I can do it, then remove myself.

### CODE REVIEW

**Comment by ctrueden** [comment]
@kapoorlab Please merge, so that CI builds can work again for this project.

**Comment by kapoorlab** [comment]
Thanks @ctrueden, its done.

**Comment by ctrueden** [comment]
@kapoorlab Thanks! Now all we need to do is add the maven.scijava.org deployment secrets. Normally the way this works is to add the six environment variable key/value pairs to the organization's Secrets section, so that all repositories in the organization can deploy to maven.scjiava.org without any further effort. However, this repository is in your user space rather than an organization, so we won't be able to use the same process. I think we'll just have to add the secrets to this repository only, and then in future, if you have additional projects wanting to deploy to maven.scijava.org, they will need to be set up separately.

So your options are:

A) Invite me as co-owner of this repository. I will add the secrets, then remove myself from the repository; or:
B) Move this repository to an organization, then invite me as co-owner of the org, and I will add the secrets there, then leave the org.

Option (A) will work only for this repository, whereas (B) would set you up for deployment more extensibly.

How would you like to proceed?

**Comment by kapoorlab** [comment]
@ctrueden I created a new organization called kapoorlabs-paris and forked the code over there and added you as an owner. Would this work?

**Comment by ctrueden** [comment]
Yes, that will work. Although I would suggest instead of forking, just move the repository. You can go to settings and transfer. Then you won't have multiple confusing forks floating around, where the original code source isn't actually the one running the CI.

**Comment by ctrueden** [comment]
I have added the secrets to `kapoorlabs-paris`. You'll want to make sure that the contents of MTrack's `pom.xml` match that org. After that, builds should start deploying successfully to maven.scijava.org. Please let me know if you notice any problems with it.

**Comment by kapoorlab** [comment]
Thanks a lot @ctrueden, I will check and report if there are any issues.

**Pull request merged**
